version: '3'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - mynetwork2

  web-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./html:/var/www/html/
    ports:
      - "8080:80"
    restart: always
    links:
      - db
    networks:
      - mynetwork2
    
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static_pages:/usr/share/nginx/html
    ports:
      - "9000:80"
    depends_on:
      - web-server
    networks:
      - mynetwork2

volumes:
  db_data:
networks:
  mynetwork2: